name: recept_skafferiet
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  mongo_dart: ^0.3.4
  crypto: ^2.1.3
  uuid: ^2.0.2
  web_scraper: ^0.1.4
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

