name: recept_skafferiet_server
publish_to: none # not intended for publication to pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  shelf: ^1.2.0
  shelf_router: ^1.0.0
  shelf_static: any
  mongo_dart: any

dev_dependencies:
  http: ^0.13.0
  lints: ^1.0.0
  test: ^1.15.0
  test_process: ^2.0.0
